#pragma config(Sensor, S1,     leftSensor,     sensorLightActive)
#pragma config(Sensor, S2,     rightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     HTleft,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTright,        sensorI2CCustom)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          centMotor,     tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


#include "header/hitechnic-colour-v2.h"
#include <include/Init.c>
#include <include/SensorsTools.c>
#include <include/Tools.c>
#include <include/colorsDetection.c>
#include <include/MovementTools.c>
#include <include/TachoPID.c>
#include <include/LinePID.c>
#include <include/Turns.c>
#include <include/Manipulators.c>
#include <include/Route.c>
#include <include/scanning.c>
#include <include/Logic.c>

task main()
{
	//check_battery();

	setSoundVolume(70);

	InitMarkerCallibrationRaw();
	InitWashCallibrationRaw();

	initSensor(&colorRightSensor, HTright, HTCS2_MODE_RAW);
	initSensor(&colorLeftSensor, HTleft, HTCS2_MODE_RAW);

	startTask(openGraber);

	start();
	sleep(50000000);
	pair* pair_blueYellow = Rooms_blueYellow();
	int wash_blueRoom = pair_blueYellow->first;
	int wash_yellowRoom = pair_blueYellow->second;

	moveFromFirstPairRoomsToFrames();
	readFrames();
	frames(wash_blueRoom, wash_yellowRoom);
	moveFromFramesToSecondPair();

	pair* pair_redGreen = Rooms_redGreen();
	int wash_redRoom = pair_redGreen->first;
	int wash_greenRoom = pair_redGreen->second;

	moveFromSecondPairRoomsToFrames();
	frames(wash_redRoom, wash_greenRoom);

	finish();
}
