#pragma config(Sensor, S1,     leftSensor,     sensorLightActive)
#pragma config(Sensor, S2,     rightSensor,    sensorLightActive)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          centMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Sensor, S3,     HTleft,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTright,        sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "header/hitechnic-EOPD.h"
#include "header/hitechnic-colour-v2.h"
#include <include/Init.c>
#include <include/SensorsTools.c>
#include <include/Tools.c>
#include <include/colorsDetection.c>
#include <include/MovementTools.c>
#include <include/TachoPID.c>
#include <include/LinePID.c>
#include <include/Turns.c>
#include <include/Manipulators.c>
#include <include/Route.c>
#include <include/scanning.c>
#include <include/Logic.c>

task main()
{

	int wash_blueRoom;
	int wash_yellowRoom;

	setSoundVolume(10);
	check_battery();
	setSoundVolume(10);

	InitMarkerCallibrationRaw();
	InitWashCallibrationRaw();
	InitCallibrationFamesInfoRaw();

	initSensor(&colorRightSensor, HTright, HTCS2_MODE_RAW);
	initSensor(&colorLeftSensor,  HTleft,  HTCS2_MODE_RAW);

	startTask(openGraber);

	global_water_left = 1;
	global_water_right = 1;

	start();

	pair* pair_blueYellow = Rooms_blueYellow();
	wash_blueRoom = pair_blueYellow->first;
	wash_yellowRoom = pair_blueYellow->second;

	BrakeLeftRightMotor(1);
	eraseDisplay();
	displayCenteredTextLine(10, "blueRoom: %d  yellowRoom: %d", wash_blueRoom, wash_yellowRoom);

	moveFromFirstPairRoomsToFrames();
	readFrames();
	frames(wash_blueRoom, wash_yellowRoom);
	moveFromFramesToSecondPair();

	pair* pair_redGreen = Rooms_redGreen();
	int wash_redRoom = pair_redGreen->first;
	int wash_greenRoom = pair_redGreen->second;

	moveFromSecondPairRoomsToFrames();
	frames(wash_redRoom, wash_greenRoom);

	finish();
}
