#pragma config(Sensor, S1,     leftSensor,     sensorLightActive)
#pragma config(Sensor, S2,     rightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     HTleft,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTright,        sensorI2CCustom)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorC,          grabMotor,     tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          centMotor,     tmotorEV3_Medium, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "header/logging.h"
#include "header/hitechnic-EOPD.h"
#include "header/hitechnic-colour-v2.h"
#include <include/Init.c>
#include <include/SensorsTools.c>
#include <include/Tools.c>
#include <include/colorsDetection.c>
#include <include/MovementTools.c>
#include <include/TachoPID.c>
#include <include/LinePID.c>
#include <include/Turns.c>
#include <include/Manipulators.c>
#include <include/Route.c>
#include <include/scanning.c>
#include <include/Logic.c>

task main()
{
	setSoundVolume(10);
	check_battery();
	setSoundVolume(10);

	InitMarkerCallibrationRaw();
	InitWashCallibrationRaw();
	InitCallibrationFamesInfoRaw();

	initSensor(&colorRightSensor, HTright, HTCS2_MODE_RAW);
	initSensor(&colorLeftSensor,  HTleft,  HTCS2_MODE_RAW);

	//TakeBottles();

	startTask(motorWaterFullDown);
	waitTask(&taskFlag_motorWaterFullDown);

	startTask(setNormAfterWaterFullDown);
	waitTask(&taskFlag_setNormAfterWaterFullDown);

	motor[grabMotor] = -30;
	delay(2000);
	motor[grabMotor] = 0;

	AccelerationLinePID(100, 1, 0);
	readIndicators();
	RightRoom();
	LeftRoom();
	fromFirstPairRoomsToFrames();
	BrakeLeftRightMotor(1);
	sleep(2000);
}
